### ISSUE TITLE
Point in time should explicitly state Zulu time.

### ISSUE THREAD

**Issue by rickbeerendonk** [cognitect/transit-format#16]
m tag:
This extension has no timezone attached nor is a required timezone specified. The Java source code seems to expect Zulu time.
Isn't it wise to explicitly state that in the Transit-format specification?

t tag:
This extension's example contains a Z, which is Zulu time.
Can the t tag be anything else then Zulu time?

**Comment by alexanderkiel** [comment]
+1 The timezone handling needs clarification.

Being able to specify a timezone is important to some applications. Supporting the full RFC 3339 in non-verbose cases would be a good thing. An optional third element could be added to the array representation used for MsgPack were the absence of that element means Zulu time (as right now) and an integer means an offset in minutes according RFC 3339. I'm not sure about the string representation currently used in non-verbose JSON. I don't know why it was chooses over an array representation like in MsgPack. Maybe JSON Numbers are not as performant for longs or the bigger payload was considered important. If I'm right it would be even possible to use the current string representation for Zulu time and an array representation with the same tag for times with timezone offsets.

**Comment by dchelimsky** [comment]
@alexanderkiel you're bringing up (at least) two different issues: the semantics of a point in time and the choice of representation(s). Speaking only about the semantics, a point in time does not have a time zone. Right now is right now whether I'm in Chicago, IL, USA or Leipzig, Germany. The fact that one of the representations includes a "Z" is an artifact of that representation. You can think of it as indicating the absence of a time zone, rather than specifying one.

**Comment by jlouis** [comment]
Another important point is that once you grab time zones and include them into your format, you force every implementation to handle this. In turn, it becomes much harder to correctly define new implementations. Some languages handle time zones far better than other languages.

I'd suggest defining an extended type on your own if you need TZ support, and keep points-in-time as UTC. Then calculate the timezone offset from UTC based on the TZ data you provide.

A more valid concern is how Transit handles the leap second at the end of this month, since POSIX isn't able to handle it.

**Comment by alexanderkiel** [comment]
@dchelimsky you are right when you say that a point in time has no time zone. But adding a time zone conveys additional information which may be useful. Quoting RFC 3339:

>The offset between local time and UTC is often useful information.
>For example, in electronic mail (RFC2822, [IMAIL-UPDATE]) the local
>offset provides a useful heuristic to determine the probability of a
>prompt response.

@jlouis I would be completely fine if the semantic type `point in time` doesn't support time zones at all. But that has to be clarified because the non-verbose representation refers to RFC 3339 which has time zone support.

**Comment by dchelimsky** [comment]
The reference to RFC 3339 is for the verbose json _representation_ of a point in time, not its definition. Agreed that this should be clarified in the spec (leaving this open for now to keep that on the radar). Also agreed that a custom extension type is the way to go if you're looking to extend point in time with time zone information.

**Comment by dchelimsky** [comment]
Changed to read "timestamp (RFC 3339, no offset)"

**Comment by alexanderkiel** [comment]
Was done in b34a014929fec891ff8100cf2418dc67e23c54a0
