### ISSUE TITLE
Any C++ Implementations?

### ISSUE THREAD

**Issue by benjaminy** [cognitect/transit-format#42]
Apologies if this is the wrong place or way to ask about this, but my few minutes of googling around didn't turn up any C++ transit implementations. Does anyone know if there are any?

**Comment by puredanger** [comment]
There is a page for community implementations at https://github.com/cognitect/transit-format/wiki/Community-Implementations but there is no C++ impl there. If you want to write one, go for it!

**Comment by ArtGangsta** [comment]
@puredanger please add the community-implementations link to the main readme so people considering using the language would not reject it simply because they think there's no implementation for a language they need to interoperate with.   The list in the READ me is limited and makes it look like there are no other implementations.  Transit is a  generic enough term that locating it via google doesn't locate the above link.

**Comment by puredanger** [comment]
It's there already?  https://github.com/cognitect/transit-format/blob/master/README.md?plain=1#L40
